"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['__main__.py']
APP_NAME = "Mycobacterial CRISPRi Primer Designer"
DATA_FILES = []
OPTIONS = {
	'argv_emulation': False,
	'plist': {
	'CFBundleName': APP_NAME,
	'CFBundleDisplayName': APP_NAME,
	'CFBundleGetInfoString': "A lightweight tool to aid in the design of primers for CRISPRi sgRNAs.",
	'CFBundleVersion': "0.1.5",
	'CFBundleShortVersionString': "0.1.5",
	'NSHumanReadableCopyright': u"Copyright \xa9 2019, Christian Gauthier, All Rights Reserved."
	}
}

setup(
    name=APP_NAME,
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
